name: Build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2-beta
      - run: go build .
      - uses: actions/upload-artifact@v1
        with:
          name: terraform-provider-zeit
          path: terraform-provider-zeit
